title: JJeong's blog
logo: /assets/img/redwit-julia.png
email: kjhrlawjdgus@kaist.ac.kr
description: 개발 블로그
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Jeonghyun109
  # - name: LinkedIn
  #   icon: <i class="fa-brands fa-linkedin"></i>
  #   link: https://www.linkedin.com/in/vaibhavvikas

navigation:
  - name: Home
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: About Me
    link: ./another-page.html
  - name: Computer Science
    link: ./computer-science.html

remote_theme: vaibhavvikas/jekyll-theme-minimalistic
